project:
  type: website
  pre-render: pre_render/provider_reports.R
  render:
    - "*.qmd"

website:
  title: "WIN_data_ingest"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - provider_reports/provider_reports.qmd
      - href: https://github.com/USF-IMaRS/WIN_data_ingest
        text: Source Code on GitHub
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    message: false
    warning: false


