project:
  type: website
  pre-render: 
    - pre_render/createAllDataRaw.R
    - pre_render/provider_reports.R
    - pre_render/analyte_reports.R
  render:
    - index.qmd
    - seacar-check.qmd
    - analyte_reports/analyte_reports/*.qmd
    - analyte_reports/analyte_reports.qmd
    - provider_reports/provider_reports/*.qmd
    - provider_reports/provider_reports.qmd
  post-render:
    - scripts/rm-csv-files.sh
    
website:
  title: "FCRWQDC Ingest Reports"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - analyte_reports/analyte_reports.qmd
      - provider_reports/provider_reports.qmd
      - href: seacar-check.qmd
        text: SEACAR Export
      - href: https://github.com/USF-IMaRS/WIN_data_ingest
        text: Source Code on GitHub
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    message: false
    warning: false


