getListOfAnalytes <- function(){
  # NOTE: instead of reading all data here, we hardcode the list of analytes
  analytes <- c(
    "Temperature",
    "Salinity",
    "Ammonium",
    "Nitrite",
    "Nitrate",
    "Nitrate+Nitrite",
    "Phosphate",
    "Silicate",
    "Chlorophyll a",
    "Pheophytin",
    "Dissolved Oxygen (Discrete)",
    "Dissolved Oxygen (CTD)",
    "Dissolved Oxygen",
    "Water Temperature",
    "pH",
    "Specific Conductivity",
    "Turbidity",
    "Total Kjeldahl Nitrogen",
    "NO2+3, Filtered",
    "Total Phosphorus",
    "Total Nitrogen",
    "Fecal Coliforms",
    "Enterococci",
    "Field pH",
    "Field Temperature",
    "Field Specific Conductance",
    "Oxygen, Dissolved",
    "Nitrogen, Ammonia",
    "Nitrogen, Kjeldahl, Total",
    "Nitrogen, NO2 plus NO3",
    "Phosphorus, Total (as P) LL",
    "Nitrate-Nitrite (N)",
    "Nitrogen- Total Kjeldahl",
    "Phosphorus- Total",
    "Ammonia (N)",
    "Chlorophyll a, free of pheophytin",
    "Temperature, Water",
    "Orthophosphate (P)",
    "Chlorophyll a- corrected",
    "Nitrite (N)",
    "Nitrogen- Total",
    "Silica (SiO2)",
    "Chlorophyll a- uncorrected",
    "Nitrate (N)"
  )
  analytes <- gsub("[ \\(\\)|,]", "_", analytes)

  return(analytes)
}